apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: v1
  stringData:
    SSO_ACCOUNT_HOST_URL: ${SSO_ACCOUNT_HOST_URL}
    SSO_REALM: ${SSO_REALM}
    SSO_CLIENT_ID: ${SSO_CLIENT_ID}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: reggie-web-sso-account
  type: Opaque
parameters:
- description: A base url of sso in the env
  displayName: SSO_ACCOUNT_HOST_URL
  name: SSO_ACCOUNT_HOST_URL
  required: true
  value: ''
- description: A sso realm name in the env
  displayName: SSO_REALM
  name: SSO_REALM
  required: true
  value: ''
- description: A sso client
  displayName: SSO_CLIENT_ID
  name: SSO_CLIENT_ID
  required: true
  value: ''
  