apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: v1
  stringData:
    EMAIL_HOST: ${EMAIL_HOST}
    EMAIL_PORT: ${EMAIL_PORT}
    EMAIL_SENDER: ${EMAIL_SENDER}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: reggie-email-server
  type: Opaque
parameters:
- description: A email server host url
  displayName: EMAIL_HOST
  name: EMAIL_HOST
  required: true
  value: ''
- description: A email server host port
  displayName: EMAIL_PORT
  name: EMAIL_PORT
  required: true
  value: ''
- description: A email server sender
  displayName: EMAIL_SENDER
  name: EMAIL_SENDER
  required: true
  value: ''
