apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: v1
  stringData:
    CONFIRMATION: ${CONFIRMATION}
    INVITATION: ${INVITATION}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: reggie-email-jwt
  type: Opaque
parameters:
- description: A confirmatipon secret
  displayName: EMAIL_HOST
  name: EMAIL_HOST
  required: true
  value: ''
- description: A invitation secret
  displayName: INVITATION
  name: INVITATION
  required: true
  value: ''
