apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: v1
  stringData:
    SSO_ADMIN_ACCOUNT_HOST_URL: ${SSO_ADMIN_ACCOUNT_HOST_URL}
    SSO_ADMIN_ACCOUNT_REALM: ${SSO_ADMIN_ACCOUNT_REALM}
    SSO_ADMIN_ACCOUNT_USERNAME: ${SSO_ADMIN_ACCOUNT_USERNAME}
    SSO_ADMIN_ACCOUNT_PASSWORD: ${SSO_ADMIN_ACCOUNT_PASSWORD}
    SSO_API_CLIENT_SECRET: ${SSO_API_CLIENT_SECRET}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: reggie-sso-account
  type: Opaque
parameters:
- description: A base url of sso in the env
  displayName: SSO_ADMIN_ACCOUNT_HOST_URL
  name: SSO_ADMIN_ACCOUNT_HOST_URL
  required: true
  value: ''
- description: A sso realm name in the env
  displayName: SSO_ADMIN_ACCOUNT_REALM
  name: SSO_ADMIN_ACCOUNT_REALM
  required: true
  value: ''
- description: A sso admin username
  displayName: SSO_ADMIN_ACCOUNT_USERNAME
  name: SSO_ADMIN_ACCOUNT_USERNAME
  required: true
  value: ''
- description: A sso admin password
  displayName: SSO_ADMIN_ACCOUNT_PASSWORD
  name: SSO_ADMIN_ACCOUNT_PASSWORD
  required: true
  value: ''
- description: A secret for reggie web to connect to api
  displayName: SSO_API_CLIENT_SECRET
  name: SSO_API_CLIENT_SECRET
  required: true
  value: ''
  